version: '2'
services:
    metabase:
        image: metabase/metabase
        #build: .
        volumes:
            - ~/metabase-data:/metabase-data
        ports:
            - "3000:3000"
        restart: always
        environment:
          VIRTUAL_HOST: metabase.example.com

networks:
  default:
    external:
      name: shared
