version: "2"
services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
    restart: always
    logging:
      options:
        max-size: 5m
        max-file: "10"

  pgsql9:
      image: postgres:9
      container_name: pgsql9
      #environment:
          #- POSTGRES_USER=postgres
          #- POSTGRES_PASSWORD=admin123
          #- POSTGRES_DB=knowledge_production
      volumes:
          #- ./volumes/initdb:/docker-entrypoint-initdb.d
          - ./volumes/postgres/data:/var/lib/postgresql/data
      restart: always
      ports:
          - "15432:5432"


networks:
  default:
    external:
      name: shared
